### PR TITLE
Sanketr113

### PR DESCRIPTION
**Pull request by Sanketr113**
Added a new logo to the app
Modified the UI
Added a lottie animation to  the home page

### CODE REVIEW

**Comment by Sanketr113** [comment]
> Added a new logo to the app Modified the UI Added a lottie animation to the home page

you need to add a package lottie

**Comment by HemantPra389** [comment]
You must need to update the png image of app if you have done some changes and make sure it works fine

**Comment by Sanketr113** [comment]
> You must need to update the png image of app if you have done some changes and make sure it works fine



> You must need to update the png image of app if you have done some changes and make sure it works fine



> You must need to update the png image of app if you have done some changes and make sure it works fine

I have shared images of the working app in the images folder in the bmi calculattor please check it onse

**Comment by Sanketr113** [comment]
Screenshot_20221004-200416
Screenshot_20221004-200431_One UI Home

**Comment by Sanketr113** [comment]
> Screenshot_20221004-200416 Screenshot_20221004-200431_One UI Home

pls see this screen shot i shared it in the bmi calculator too the cycle is a animation and also the logo of the app is changed

**Comment by HemantPra389** [comment]
Wow that's an amazing work.Thanks to you.
Follow your the maintainer and share your love with us and star the repo.
Happy Hacktoberfest2022!!
Your changes will get merge after 10 min

**Comment by Sanketr113** [comment]
Thank you for your response. I am glad to hear that.

**Pull request merged**
