### PR TITLE
Added Color Detector/TTS Flutter Application for Beginners

### PR DESCRIPTION
**Pull request by VaibhavdLights**

### CODE REVIEW

**Comment by HemantPra389** [comment]
Yeah you really done a mind blowing work..
Will you please add your image screenshot in readme.
Happy Hacktoberfest2022!!!!!!!!

**Comment by VaibhavdLights** [comment]
Done @HemantPra389

**Comment by HemantPra389** [comment]
Yess absolutely you're some of our top contributors. We will be merging your pr until then follow the maintainer and star ⭐ the repository to show some support.

**Comment by VaibhavdLights** [comment]
Done @HemantPra389

**Pull request merged**
