### PR TITLE
Added th app

### PR DESCRIPTION
**Pull request by siddharth1729**
Hii @HemantPra389 

I have pushed the app pleas review and do let me know the chnges

### CODE REVIEW

**Comment by HemantPra389** [comment]
Wow That's a wonderful work. 
Star the repo and share your love to opensource
Happy Hacktoberfest2022!!!!!!!!!!

**Comment by siddharth1729** [comment]
Hii @HemantPra389 

Pleas add the hactoberfest tag so that i will be consided

**Comment by HemantPra389** [comment]
Thankyou for participating Follow the maintainer and share some love

**Comment by siddharth1729** [comment]
Thankd buddy

**Pull request merged**
