### PR TITLE
GroupChatApp added

### PR DESCRIPTION
**Pull request by dubey2709**
Added A flutter made group chat application

### CODE REVIEW

**Comment by HemantPra389** [comment]
Sorry But you mistakenly uploaded the changes in the wrong folder. Please make sure to upload in a proper folder structure:)
Happy Hacktoberfest2022!!!

**Comment by dubey2709** [comment]
In which folder I should upload?
Or is it fine

**Comment by HemantPra389** [comment]
You can upload that in your app level folder intermediate or else and can upload your folder there like others

**Comment by HemantPra389** [comment]
Please Add some images of your app and show them in your readme that will be more impactful.
Happy Hacktoberfest2022!!!!!

**Comment by dubey2709** [comment]
Sir Added..Now I have done my best

**Comment by HemantPra389** [comment]
Wow You Achieved the best of your project.
Star the repo and share your love with us
Happy Hacktoberfest2022!!!!!!!

**Comment by dubey2709** [comment]
Sir if possible add gha hacktoberfesrt accepted label

**Comment by HemantPra389** [comment]
What do you mean by gha?? Be clear with your problem please ☺️

**Comment by dubey2709** [comment]
*the not gha😅

**Comment by HemantPra389** [comment]
Okk I will do ASAP 😃...

**Comment by HemantPra389** [comment]
Follow the repo mentor and show your support

**Comment by dubey2709** [comment]
Done sir

**Pull request merged**
