### PR TITLE
Swiggy UI Clone

### PR DESCRIPTION
**Pull request by suyash0102**
added Swiggy UI Clone

### CODE REVIEW

**Comment by suyash0102** [comment]
Hey @HemantPra389 you can check this one.

**Comment by HemantPra389** [comment]
Yess absolutely you're some of our top contributors. We will be merging your pr until then follow the maintainer and star 🌟 the repository to show some support.

**Comment by suyash0102** [comment]
Yeah sure

**Comment by HemantPra389** [comment]
I think you mistakenly created .idea folder in the root folder of repository. You must include all specific related folders within your project folder. We really like your contribution and thinking that you may improve certain changes necessary.
Happy Hacktoberfest2022!!!!

**Comment by suyash0102** [comment]
May I remove and pull req again?

**Comment by suyash0102** [comment]
Now check @HemantPra389

**Comment by HemantPra389** [comment]
Yess you can It will be more clean approach for this problem....

**Comment by HemantPra389** [comment]
Yess it looks fine

**Pull request merged**
